import { useEffect, useMemo, useState } from 'react'
import { supabase } from './lib/supabase'

const blankLocation={location_id:'',project_id:'',parent_location_id:'',location_type:'Area',location_code:'',location_name:'',sort_order:''}
const blankPerson={person_id:'',organization_id:'',display_name:'',email:'',phone:'',job_title:'',organization_role:'member',is_external:false}
const blankVendor={vendor_id:'',organization_id:'',vendor_code:'',vendor_name:'',vendor_type:'Supplier',tax_id:'',trade_code:'',is_approved:false}

function Actions({onEdit,onDisable,disabled}){return <div className="row-actions"><button onClick={onEdit}>編輯</button><button className="danger-lite" disabled={disabled} onClick={onDisable}>停用</button></div>}

export function LocationPanel({mode,data,loadLive,setNotice}){
  const [f,setF]=useState(blankLocation)
  const projects=data.projects||[]
  useEffect(()=>{if(!f.project_id&&projects[0]?.project_id)setF(x=>({...x,project_id:projects[0].project_id}))},[projects,f.project_id])
  const parents=useMemo(()=>(data.locations||[]).filter(x=>x.project_id===f.project_id&&x.location_id!==f.location_id),[data.locations,f.project_id,f.location_id])
  const save=async(e)=>{e.preventDefault();if(mode!=='live')return;const payload={project_id:f.project_id,parent_location_id:f.parent_location_id||null,location_type:f.location_type||'Area',location_code:f.location_code||null,location_name:f.location_name,sort_order:f.sort_order===''?null:Number(f.sort_order),is_active:true};let error;if(f.location_id)({error}=await supabase.from('locations').update(payload).eq('location_id',f.location_id));else({error}=await supabase.from('locations').insert(payload));if(error)return setNotice('位置儲存失敗：'+error.message);setNotice(f.location_id?'位置已更新。':'位置已新增。');setF({...blankLocation,project_id:projects[0]?.project_id||''});await loadLive()}
  const disable=async(r)=>{if(!confirm(`停用位置「${r.location_name}」？`))return;const {error}=await supabase.from('locations').update({is_active:false}).eq('location_id',r.location_id);if(error)setNotice('位置停用失敗：'+error.message);else{setNotice('位置已停用。');await loadLive()}}
  return <section className="card"><div className="section-head"><h2>位置｜Location</h2><b>{data.locations?.length||0}</b></div><form className="crud-form" onSubmit={save}><select value={f.project_id} onChange={e=>setF({...f,project_id:e.target.value,parent_location_id:''})} required><option value="">選擇專案</option>{projects.map(p=><option key={p.project_id} value={p.project_id}>{p.project_code}｜{p.project_name}</option>)}</select><select value={f.location_type} onChange={e=>setF({...f,location_type:e.target.value})}><option>Project</option><option>Building</option><option>Floor</option><option>Zone</option><option>Unit</option><option>Area</option></select><input placeholder="位置代碼" value={f.location_code} onChange={e=>setF({...f,location_code:e.target.value})}/><input placeholder="位置名稱 *" required value={f.location_name} onChange={e=>setF({...f,location_name:e.target.value})}/><select value={f.parent_location_id} onChange={e=>setF({...f,parent_location_id:e.target.value})}><option value="">無上層位置</option>{parents.map(x=><option key={x.location_id} value={x.location_id}>{x.location_code||'-'}｜{x.location_name}</option>)}</select><input type="number" placeholder="排序" value={f.sort_order} onChange={e=>setF({...f,sort_order:e.target.value})}/><button className="primary" disabled={mode!=='live'}>{f.location_id?'儲存修改':'新增位置'}</button>{f.location_id&&<button type="button" onClick={()=>setF({...blankLocation,project_id:projects[0]?.project_id||''})}>取消</button>}</form><div className="table-wrap"><table><thead><tr><th>專案</th><th>類型</th><th>代碼</th><th>位置</th><th>上層</th><th>狀態</th><th>操作</th></tr></thead><tbody>{(data.locations||[]).map(r=><tr key={r.location_id}><td>{r.project_code}</td><td>{r.location_type}</td><td>{r.location_code}</td><td>{r.location_name}</td><td>{r.parent_location_name||''}</td><td>{r.is_active?'啟用':'停用'}</td><td><Actions disabled={!r.is_active} onEdit={()=>setF({location_id:r.location_id,project_id:r.project_id,parent_location_id:r.parent_location_id||'',location_type:r.location_type||'Area',location_code:r.location_code||'',location_name:r.location_name||'',sort_order:r.sort_order??''})} onDisable={()=>disable(r)}/></td></tr>)}</tbody></table></div></section>
}

export function PeoplePanel({mode,data,loadLive,setNotice}){
  const [f,setF]=useState(blankPerson)
  const orgs=data.organizations||[]
  useEffect(()=>{if(!f.organization_id&&orgs[0]?.organization_id)setF(x=>({...x,organization_id:orgs[0].organization_id}))},[orgs,f.organization_id])
  const save=async(e)=>{e.preventDefault();if(mode!=='live')return;const personPayload={organization_id:f.organization_id,display_name:f.display_name,email:f.email||null,phone:f.phone||null,job_title:f.job_title||null,is_external:!!f.is_external,is_active:true};let personId=f.person_id;if(personId){const {error}=await supabase.from('people').update(personPayload).eq('person_id',personId);if(error)return setNotice('人員更新失敗：'+error.message)}else{const {data:row,error}=await supabase.from('people').insert(personPayload).select('person_id').single();if(error)return setNotice('人員新增失敗：'+error.message);personId=row.person_id}
    const {data:membership}=await supabase.from('organization_members').select('organization_member_id').eq('organization_id',f.organization_id).eq('person_id',personId).maybeSingle();let mError;if(membership?.organization_member_id)({error:mError}=await supabase.from('organization_members').update({role_code:f.organization_role,is_active:true}).eq('organization_member_id',membership.organization_member_id));else({error:mError}=await supabase.from('organization_members').insert({organization_id:f.organization_id,person_id:personId,role_code:f.organization_role,is_active:true}));if(mError)return setNotice('人員已儲存，但組織角色更新失敗：'+mError.message);setNotice(f.person_id?'人員已更新。':'人員已新增。');setF({...blankPerson,organization_id:orgs[0]?.organization_id||''});await loadLive()}
  const disable=async(r)=>{if(!confirm(`停用人員「${r.display_name}」？`))return;const {error}=await supabase.from('people').update({is_active:false}).eq('person_id',r.person_id);if(error)return setNotice('人員停用失敗：'+error.message);await supabase.from('organization_members').update({is_active:false}).eq('person_id',r.person_id).eq('organization_id',r.organization_id);setNotice('人員已停用。');await loadLive()}
  return <section className="card"><div className="section-head"><h2>人員｜People</h2><b>{data.people?.length||0}</b></div><form className="crud-form" onSubmit={save}><select value={f.organization_id} onChange={e=>setF({...f,organization_id:e.target.value})} required><option value="">選擇組織</option>{orgs.map(o=><option key={o.organization_id} value={o.organization_id}>{o.organization_code}｜{o.organization_name}</option>)}</select><input placeholder="姓名 *" required value={f.display_name} onChange={e=>setF({...f,display_name:e.target.value})}/><input type="email" placeholder="Email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/><input placeholder="電話" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><input placeholder="職稱" value={f.job_title} onChange={e=>setF({...f,job_title:e.target.value})}/><select value={f.organization_role} onChange={e=>setF({...f,organization_role:e.target.value})}><option value="member">Member</option><option value="admin">Admin</option><option value="owner">Owner</option></select><label className="check-line"><input type="checkbox" checked={f.is_external} onChange={e=>setF({...f,is_external:e.target.checked})}/>外部人員</label><button className="primary" disabled={mode!=='live'}>{f.person_id?'儲存修改':'新增人員'}</button>{f.person_id&&<button type="button" onClick={()=>setF({...blankPerson,organization_id:orgs[0]?.organization_id||''})}>取消</button>}</form><div className="table-wrap"><table><thead><tr><th>姓名</th><th>職稱</th><th>Email</th><th>電話</th><th>角色</th><th>外部</th><th>狀態</th><th>操作</th></tr></thead><tbody>{(data.people||[]).map(r=><tr key={r.person_id}><td>{r.display_name}</td><td>{r.job_title}</td><td>{r.email}</td><td>{r.phone}</td><td>{r.organization_role}</td><td>{r.is_external?'是':'否'}</td><td>{r.is_active?'啟用':'停用'}</td><td><Actions disabled={!r.is_active} onEdit={()=>setF({person_id:r.person_id,organization_id:r.organization_id,display_name:r.display_name||'',email:r.email||'',phone:r.phone||'',job_title:r.job_title||'',organization_role:r.organization_role||'member',is_external:!!r.is_external})} onDisable={()=>disable(r)}/></td></tr>)}</tbody></table></div></section>
}

export function VendorPanel({mode,data,loadLive,setNotice}){
  const [f,setF]=useState(blankVendor)
  const orgs=data.organizations||[]
  useEffect(()=>{if(!f.organization_id&&orgs[0]?.organization_id)setF(x=>({...x,organization_id:orgs[0].organization_id}))},[orgs,f.organization_id])
  const save=async(e)=>{e.preventDefault();if(mode!=='live')return;const payload={organization_id:f.organization_id,vendor_code:f.vendor_code||null,vendor_name:f.vendor_name,vendor_type:f.vendor_type||'Supplier',tax_id:f.tax_id||null,trade_code:f.trade_code||null,is_approved:!!f.is_approved,is_active:true};let error;if(f.vendor_id)({error}=await supabase.from('vendors').update(payload).eq('vendor_id',f.vendor_id));else({error}=await supabase.from('vendors').insert(payload));if(error)return setNotice('廠商儲存失敗：'+error.message);setNotice(f.vendor_id?'廠商已更新。':'廠商已新增。');setF({...blankVendor,organization_id:orgs[0]?.organization_id||''});await loadLive()}
  const disable=async(r)=>{if(!confirm(`停用廠商「${r.vendor_name}」？`))return;const {error}=await supabase.from('vendors').update({is_active:false}).eq('vendor_id',r.vendor_id);if(error)setNotice('廠商停用失敗：'+error.message);else{setNotice('廠商已停用。');await loadLive()}}
  return <section className="card"><div className="section-head"><h2>廠商｜Vendor</h2><b>{data.vendors?.length||0}</b></div><form className="crud-form" onSubmit={save}><select value={f.organization_id} onChange={e=>setF({...f,organization_id:e.target.value})} required><option value="">選擇組織</option>{orgs.map(o=><option key={o.organization_id} value={o.organization_id}>{o.organization_code}｜{o.organization_name}</option>)}</select><input placeholder="廠商代碼" value={f.vendor_code} onChange={e=>setF({...f,vendor_code:e.target.value})}/><input placeholder="廠商名稱 *" required value={f.vendor_name} onChange={e=>setF({...f,vendor_name:e.target.value})}/><select value={f.vendor_type} onChange={e=>setF({...f,vendor_type:e.target.value})}><option>Supplier</option><option>Subcontractor</option><option>Consultant</option><option>Contractor</option></select><input placeholder="統一編號" value={f.tax_id} onChange={e=>setF({...f,tax_id:e.target.value})}/><input placeholder="工種／Trade Code" value={f.trade_code} onChange={e=>setF({...f,trade_code:e.target.value})}/><label className="check-line"><input type="checkbox" checked={f.is_approved} onChange={e=>setF({...f,is_approved:e.target.checked})}/>核准廠商</label><button className="primary" disabled={mode!=='live'}>{f.vendor_id?'儲存修改':'新增廠商'}</button>{f.vendor_id&&<button type="button" onClick={()=>setF({...blankVendor,organization_id:orgs[0]?.organization_id||''})}>取消</button>}</form><div className="table-wrap"><table><thead><tr><th>代碼</th><th>廠商</th><th>類型</th><th>統編</th><th>工種</th><th>核准</th><th>狀態</th><th>操作</th></tr></thead><tbody>{(data.vendors||[]).map(r=><tr key={r.vendor_id}><td>{r.vendor_code}</td><td>{r.vendor_name}</td><td>{r.vendor_type}</td><td>{r.tax_id}</td><td>{r.trade_code}</td><td>{r.is_approved?'是':'否'}</td><td>{r.is_active?'啟用':'停用'}</td><td><Actions disabled={!r.is_active} onEdit={()=>setF({vendor_id:r.vendor_id,organization_id:r.organization_id,vendor_code:r.vendor_code||'',vendor_name:r.vendor_name||'',vendor_type:r.vendor_type||'Supplier',tax_id:r.tax_id||'',trade_code:r.trade_code||'',is_approved:!!r.is_approved})} onDisable={()=>disable(r)}/></td></tr>)}</tbody></table></div></section>
}

export function CommonServicesPanel({mode,data}){
  const cards=[['recordattachments','Attachment Links｜附件連結'],['timeline','Timeline｜時間軸'],['audit','Audit｜稽核紀錄'],['recordlinks','Record Links｜跨 APP 關聯']]
  return <><div className="stats common-stats">{cards.map(([k,l])=><div className="stat" key={k}><b>{data[k]?.length||0}</b><span>{l}</span></div>)}</div><section className="card"><h2>Common Record Services｜共用紀錄服務</h2><p>這四張表是 104 APP 共用的關聯層，不屬於 SITE-DIARY 專屬資料。所有資料仍受 Organization / Project RLS 控制。</p></section><section className="card"><h2>Timeline｜時間軸</h2><div className="table-wrap"><table><thead><tr><th>時間</th><th>APP</th><th>Record</th><th>事件</th><th>標題</th><th>執行者</th></tr></thead><tbody>{(data.timeline||[]).slice(0,100).map(r=><tr key={r.timeline_event_id}><td>{r.event_at}</td><td>{r.source_app}</td><td>{r.record_type} / {r.record_id}</td><td>{r.event_type}</td><td>{r.event_title||r.event_text}</td><td>{r.actor_name}</td></tr>)}</tbody></table></div></section><section className="card"><h2>Audit｜稽核紀錄</h2><div className="table-wrap"><table><thead><tr><th>時間</th><th>APP</th><th>資料表</th><th>Record ID</th><th>操作</th><th>人員</th></tr></thead><tbody>{(data.audit||[]).slice(0,100).map(r=><tr key={r.audit_id}><td>{r.changed_at}</td><td>{r.source_app}</td><td>{r.table_name}</td><td className="mono">{r.record_id}</td><td>{r.operation}</td><td>{r.changed_by_name}</td></tr>)}</tbody></table></div></section><section className="card"><h2>Record Links｜跨 APP 關聯</h2><div className="table-wrap"><table><thead><tr><th>Source</th><th>Target</th><th>關聯</th><th>建立時間</th></tr></thead><tbody>{(data.recordlinks||[]).slice(0,100).map(r=><tr key={r.record_link_id}><td>{r.source_app} / {r.source_type} / {r.source_id}</td><td>{r.target_app} / {r.target_type} / {r.target_id}</td><td>{r.link_type}</td><td>{r.created_at}</td></tr>)}</tbody></table></div></section><section className="card"><h2>Attachment Links｜附件連結</h2><div className="table-wrap"><table><thead><tr><th>APP</th><th>Record</th><th>檔名</th><th>用途</th><th>主要附件</th></tr></thead><tbody>{(data.recordattachments||[]).slice(0,100).map(r=><tr key={r.record_attachment_id}><td>{r.source_app}</td><td>{r.record_type} / {r.record_id}</td><td>{r.file_name}</td><td>{r.purpose}</td><td>{r.is_primary?'是':'否'}</td></tr>)}</tbody></table></div></section></>
}
